### PR TITLE
setup circleci and make ipmitool usage optional

### PR DESCRIPTION
**Pull request by pmenglund**

### CODE REVIEW

**Review by dougm — APPROVED** [review]
lgtm , thanks @pmenglund !

**Comment by pmenglund** [comment]
Hi @dougm! Long time no see!

Can you enable the build in:
https://circleci.com/gh/vmware/goipmi

**Comment by dougm** [comment]
Hi @pmenglund , great to hear from you!  I'm not able to enable the build in CircleCI ("contact repo admin"), I'll look into it.

**Comment by frapposelli** [comment]
Enabled 👍

**Pull request merged**
